### ISSUE TITLE
[Request] RetroArch support

### ISSUE THREAD

**Issue by Lahiri** [JTNDev/galaxy-integration-gc#2]
First of all, thanks for the integration.

Since the emulator path is specified by the user in the user_config.py file, would it be possible to support other emulators such as RetroArch by adding command line arguments for the executable?

The same feature has been implemented in the [PSP integration](https://github.com/TBemme/galaxy-integration-psp/commit/60fdbc7f2dd3a4ccc81d600c6d2ad4757fb2e25f) so it should be easy to replicate here.

Thanks.

**Comment by JTNDev** [comment]
Yes it would, I was actually just thinking about adding support for
Retroarch!

**Comment by Lahiri** [comment]
I tested the new release where you added RetroArch support and it works really well for me. Thanks!
