### ISSUE TITLE
Incorrect Game info imported from GameTDB

### ISSUE THREAD

**Issue by Elikay** [JTNDev/galaxy-integration-gc#8]
Currently there are dozens if not hundreds of duplicates in the game list, and it seems that depending on which one comes first, changes what the actual result is when it's imported to GOG. I have instances where I've been given the 3DS version of Luigi's mansion, the Playstation 2 version of Super Monkey Ball Adventure, the Xbox version of Spongebob Battle for Bikini Bottom, and some don't show up at all. It's more than just cover art too, it's descriptions, release dates, developers, etc.

However in Dolphin, which also uses GameTDB, there's no issues at all. I'm assuming this is because it uses the actual game ID rather than grabbing a random ID with the same name. But when looking deeper at GameTDB, I'm starting to wonder if it's even using the assets from GameTDB? Is there anything that could be done to fix this? I can't manually change the games information by hand even if I wanted to, Galaxy just doesn't support it right now, but if I had to rename all my isos anyways, couldn't I just name them the exact code they are?

**Comment by JTNDev** [comment]
It has nothing to do with GameTDB it has to do with Galaxy's API. I can't
really do anything about that unfortunately until this gets integrated:
https://github.com/gogcom/galaxy-integrations-python-api/issues/49#issuecomment-522331088
